/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as siteRouteRouteImport } from './routes/(site)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as siteProductsIndexRouteImport } from './routes/(site)/products/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as siteProductsProductRouteImport } from './routes/(site)/products/$product'
import { Route as siteProductsCategoryCategoryRouteImport } from './routes/(site)/products/category/$category'

const siteRouteRoute = siteRouteRouteImport.update({
  id: '/(site)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const siteProductsIndexRoute = siteProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => siteRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const siteProductsProductRoute = siteProductsProductRouteImport.update({
  id: '/products/$product',
  path: '/products/$product',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteProductsCategoryCategoryRoute =
  siteProductsCategoryCategoryRouteImport.update({
    id: '/products/category/$category',
    path: '/products/category/$category',
    getParentRoute: () => siteRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof siteRouteRouteWithChildren
  '/products/$product': typeof siteProductsProductRoute
  '/login': typeof authLoginIndexRoute
  '/products': typeof siteProductsIndexRoute
  '/products/category/$category': typeof siteProductsCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof siteRouteRouteWithChildren
  '/products/$product': typeof siteProductsProductRoute
  '/login': typeof authLoginIndexRoute
  '/products': typeof siteProductsIndexRoute
  '/products/category/$category': typeof siteProductsCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(site)': typeof siteRouteRouteWithChildren
  '/(site)/products/$product': typeof siteProductsProductRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(site)/products/': typeof siteProductsIndexRoute
  '/(site)/products/category/$category': typeof siteProductsCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products/$product'
    | '/login'
    | '/products'
    | '/products/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/$product'
    | '/login'
    | '/products'
    | '/products/category/$category'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(site)'
    | '/(site)/products/$product'
    | '/(auth)/login/'
    | '/(site)/products/'
    | '/(site)/products/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  siteRouteRoute: typeof siteRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(site)': {
      id: '/(site)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof siteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/products/': {
      id: '/(site)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof siteProductsIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(site)/products/$product': {
      id: '/(site)/products/$product'
      path: '/products/$product'
      fullPath: '/products/$product'
      preLoaderRoute: typeof siteProductsProductRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/products/category/$category': {
      id: '/(site)/products/category/$category'
      path: '/products/category/$category'
      fullPath: '/products/category/$category'
      preLoaderRoute: typeof siteProductsCategoryCategoryRouteImport
      parentRoute: typeof siteRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface siteRouteRouteChildren {
  siteProductsProductRoute: typeof siteProductsProductRoute
  siteProductsIndexRoute: typeof siteProductsIndexRoute
  siteProductsCategoryCategoryRoute: typeof siteProductsCategoryCategoryRoute
}

const siteRouteRouteChildren: siteRouteRouteChildren = {
  siteProductsProductRoute: siteProductsProductRoute,
  siteProductsIndexRoute: siteProductsIndexRoute,
  siteProductsCategoryCategoryRoute: siteProductsCategoryCategoryRoute,
}

const siteRouteRouteWithChildren = siteRouteRoute._addFileChildren(
  siteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  siteRouteRoute: siteRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
